# Generated by Django 3.0.11 on 2021-01-29 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کوپن تخفیف')),
                ('valid_from', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('valid_to', models.DateTimeField(verbose_name='انقضاء')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف')),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'تنظیمات طرح تخفیف',
            },
        ),
    ]
