# Generated by Django 3.0.11 on 2021-01-29 13:55

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='نام- دسته بندی')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoping.Category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'دسته بندی محصولات',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='نام')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateField(auto_now=True, verbose_name='تاریخ تغییر')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscatégories', to='shoping.Category')),
            ],
            options={
                'verbose_name': 'زیر منو',
                'verbose_name_plural': 'زیر منوها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='نام کالا')),
                ('slug', models.SlugField(max_length=200)),
                ('image1', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='تصویر اول')),
                ('image2', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='تصویر دوم')),
                ('description', models.TextField(blank=True, verbose_name='شرح کالا')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت کالا')),
                ('available', models.BooleanField(default=True, verbose_name='موجودی')),
                ('color', models.CharField(max_length=10, null=True, verbose_name='رنگ کالا')),
                ('country', models.CharField(max_length=30, verbose_name='کشور سازنده')),
                ('created', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', django_jalali.db.models.jDateField(auto_now=True, verbose_name='تاریخ تغییر')),
                ('new_category', models.BooleanField(default=True, verbose_name='ویژه')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shoping.Category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='shoping.SubCategory')),
            ],
            options={
                'verbose_name_plural': 'محصول',
                'ordering': ('created',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
